payment:
  replicaCount: 1
  image:
    repository: ghcr.io/amirweiser/paymentservice
    tag: 6c796bc0d3d17a539eff5f853b9bbd1859046e36
productCatalog:
  replicaCount: 1
  image:
    repository: ghcr.io/amirweiser/product-catalog
    tag: cbd7bcd47792b496c7d5f2b93c2befae916d2d90
