payment:
  replicaCount: 1
  image:
    repository: ghcr.io/amirweiser/paymentservice
    tag: 6c796bc0d3d17a539eff5f853b9bbd1859046e36
productCatalog:
  replicaCount: 1
  image:
    repository: ghcr.io/amirweiser/product-catalog
    tag: 99b515cc840b1b730673cc28c9b73c01646d5e37
